#!/usr/bin/env ruby

source = File.dirname(File.realpath(__FILE__))
target = ENV['HOME']

Dir["#{source}/.*"].each do |file|
  next if File.directory?(file)
  next if file =~ /(?:\.sw\w|\.gitignore)$/

  dest = File.join(target, File.basename(file))
  print "\033[1;32m▶\033[0m #{dest} \033[1;32m→\033[0m #{file} "
  begin
    File.symlink(file, dest)
    puts "\033[1;31m❤\033[0m"
  rescue => e
    puts "\033[1;33m╳ #{e.message}\033[0m"
  end
end
