#!/bin/bash

# Initial welcome setup, currently only for Git config
#
[ "$1" != "setup" ] && interactive='yay'
changed=

user_name=$(git config --global user.name)

configure_git() {

  [ "$user_name" != 'Rails Girl' ] && configured='yay'

  if [ "$interactive" -o ! "$configured" ]; then
    echo -en "\033[1;31m❤\033[0m Can you please tell me your name? "
    read
    local _name=$REPLY
    echo -e "\033[1;31m❤\033[0m OH! \033[1;37m$_name\033[0m is a very nice name! Thank you! \033[1;33m:-)\033[0m"
    echo

    echo -en "\033[1;31m❤\033[0m May I also know your e-mail? "
    read
    local _mail=$REPLY
    echo -e "\033[1;31m❤\033[0m OK, thanks again!"

    git config --global user.name  "$_name"
    git config --global user.email "$_mail"
    changed='yay'
  fi

}

cat ~/.railsgirls/banner

echo
echo
echo -e "\033[1;31m❤ ❤ ❤\033[0m Welcome $user_name! \033[1;31m❤ ❤ ❤\033[0m"
echo

configure_git

if [ "$changed" ]; then
  echo
  echo -e "\033[1;31m❤\033[0m I've configured this Rails Engine just for you! \033[1;33m:-)\033[0m"
  echo

  if [ !"$interactive" ]; then
    echo "If you want to configure again, type:"
    echo
    echo -e "  \033[1;37mwelcome\033[0m"
    echo
  fi
fi

if [ ! "$interactive" ]; then
  echo "To run the interactive Ruby console, type:"
  echo
  echo -e "  [1;37mRuby[0m"
  echo
  echo 'To create a new Rails app named "myapp" type:'
  echo
  echo -e "  [1;37mrails new code/myapp[0m"
  echo
fi

echo -e "[1;32mHave fun! :-)[0m"
