#!/bin/bash

# Initial welcome setup, currently only for Git config
#
[ "$1" != "setup" ] && interactive='yay'
changed=

user_name=$(git config --global user.name)

configure_git() {

  [ "$user_name" != 'Rails Girl' ] && configured='yay'

  if [ "$interactive" -o ! "$configured" ]; then
    local _name _mail

    while [ ! "$_name" ]; do
      echo -en "\033[1;31m❤\033[0m Can you please tell me your name? "
      read
      local _name=$REPLY
    done

    echo -e "\033[1;31m❤\033[0m OH! \033[1;37m$_name\033[0m is a very nice name! Thank you! \033[1;33m:-)\033[0m"
    echo

    while [ ! "$_mail" ]; do
      echo -en "\033[1;31m❤\033[0m May I also know your e-mail? "
      read
      local _mail=$REPLY
    done
    echo -e "\033[1;31m❤\033[0m OK, thanks again!"

    git config --global user.name  "$_name"
    git config --global user.email "$_mail"
    changed='yay'
  fi

}

if [ ! "$interactive" ]; then
  cat ~/.railsgirls/banner

  echo
  echo -e "\033[1;31m❤ ❤ ❤\033[0m Welcome $user_name! \033[1;31m❤ ❤ ❤\033[0m"
  echo
fi

configure_git

if [ "$changed" ]; then
  echo
  echo -e "\033[1;31m❤\033[0m The Rails Engine is now customized, just for you! \033[1;33m:-)\033[0m"
  echo

  if [ ! "$interactive" ]; then
    echo "If you want to customize again, type:"
    echo
    echo -e "  \033[1;37mwelcome\033[0m"
    echo
  fi
fi

if [ ! "$interactive" ]; then
  echo "To run the interactive Ruby console, type:"
  echo
  echo -e "  [1;37mRuby[0m"
  echo
  echo 'To create a new Rails app named "myapp" type:'
  echo
  echo -e "  [1;37mrails new code/myapp[0m"
  echo
fi

echo -e "[1;32mHave fun! :-)[0m"
echo
